/******************************************************************************
*  Generated by PSoC Designer 5.4.2927
******************************************************************************/
// =============================================================================
// FILENAME: PSoCAPI.h
// 
// Copyright (c) Cypress Semiconductor 2013. All Rights Reserved.
// 
// NOTES:
// Do not modify this file. It is generated by PSoC Designer each time the
// generate application function is run. The values of the parameters in this
// file can be modified by changing the values of the global parameters in the
// device editor.
// 
// =============================================================================
 
#ifndef __PSOCAPI_H
#define __PSOCAPI_H

#include "PSoCGPIOINT.h"
#include "AMUX4.h"
#include "BackLeftMotor_N.h"
#include "BackLeftMotor_P.h"
#include "BackRightMotor_N.h"
#include "BackRightMotor_P.h"
#include "I2Cs.h"
#include "Range_ADC.h"
#include "Range_PGA.h"
#include "Servo_PWM.h"

#endif
