/******************************************************************************
*  Generated by PSoC Designer 5.4.2927
******************************************************************************/
#include <m8c.h>
// I2CsSDA address and mask defines
#pragma	ioport	I2CsSDA_Data_ADDR:	0x4
BYTE			I2CsSDA_Data_ADDR;
#pragma	ioport	I2CsSDA_DriveMode_0_ADDR:	0x104
BYTE			I2CsSDA_DriveMode_0_ADDR;
#pragma	ioport	I2CsSDA_DriveMode_1_ADDR:	0x105
BYTE			I2CsSDA_DriveMode_1_ADDR;
#pragma	ioport	I2CsSDA_DriveMode_2_ADDR:	0x7
BYTE			I2CsSDA_DriveMode_2_ADDR;
#pragma	ioport	I2CsSDA_GlobalSelect_ADDR:	0x6
BYTE			I2CsSDA_GlobalSelect_ADDR;
#pragma	ioport	I2CsSDA_IntCtrl_0_ADDR:	0x106
BYTE			I2CsSDA_IntCtrl_0_ADDR;
#pragma	ioport	I2CsSDA_IntCtrl_1_ADDR:	0x107
BYTE			I2CsSDA_IntCtrl_1_ADDR;
#pragma	ioport	I2CsSDA_IntEn_ADDR:	0x5
BYTE			I2CsSDA_IntEn_ADDR;
#define I2CsSDA_MASK 0x1
// I2CsSCL address and mask defines
#pragma	ioport	I2CsSCL_Data_ADDR:	0x4
BYTE			I2CsSCL_Data_ADDR;
#pragma	ioport	I2CsSCL_DriveMode_0_ADDR:	0x104
BYTE			I2CsSCL_DriveMode_0_ADDR;
#pragma	ioport	I2CsSCL_DriveMode_1_ADDR:	0x105
BYTE			I2CsSCL_DriveMode_1_ADDR;
#pragma	ioport	I2CsSCL_DriveMode_2_ADDR:	0x7
BYTE			I2CsSCL_DriveMode_2_ADDR;
#pragma	ioport	I2CsSCL_GlobalSelect_ADDR:	0x6
BYTE			I2CsSCL_GlobalSelect_ADDR;
#pragma	ioport	I2CsSCL_IntCtrl_0_ADDR:	0x106
BYTE			I2CsSCL_IntCtrl_0_ADDR;
#pragma	ioport	I2CsSCL_IntCtrl_1_ADDR:	0x107
BYTE			I2CsSCL_IntCtrl_1_ADDR;
#pragma	ioport	I2CsSCL_IntEn_ADDR:	0x5
BYTE			I2CsSCL_IntEn_ADDR;
#define I2CsSCL_MASK 0x2
