PROJNAME=RPi_Robot
DEVICE=CY8C29466
BASEDEVICE=CY8C29000
PROJPATH=C:/Users/KUK~1.IWP/Desktop/Robot/RPI_RO~1/RPI_RO~1/RPI_RO~1
PSOCDIR=C:/PROGRA~2/Cypress/PSOCDE~1/5.4/Common/CY110F~1
INCLUDE_PATH=C:/PROGRA~2/Cypress/PSOCDE~1/5.4/Common/CY110F~1/tools/include/CY8C29~1
CSRCS= main.c
LIBCSRCS=
STDCSRCS=
ASMSRCS= delay.asm
LIBASMSRCS= amux4.asm backleftmotor_n.asm backleftmotor_nint.asm backleftmotor_p.asm backleftmotor_pint.asm backrightmotor_n.asm backrightmotor_nint.asm backrightmotor_p.asm backrightmotor_pint.asm i2cs.asm i2csint.asm psocconfig.asm psocconfigtbl.asm range_adc.asm range_adcint.asm range_pga.asm servo_pwm.asm servo_pwmint.asm
STDASMSRCS=
OBJECT_SOURCES= delay.asm main.c
FILLVALUE=0x30
LASTROM=0x7fff
IMAGECRAFTPRO_PATH=c:\iccv8m8c
LASTRAM=0x7ff
LAST_DATARAM=0x6ff
CODECOMPRESSOR=
MORE_CFLAGS=-Wf-Osize -Wf-LMM8 -D_LMM -Wf-O48 -Wl-elim
RELSTART=0x1a0
INC_PATH=
CDEFINES=
LIBS=
UMLIBS=
LIB_PATH=
ENABLE_ALIGN_SHIFT=0
LMM=1
SYS_INC_CONTENTS:=SYSTEM_STACK_PAGE:_equ_7 SYSTEM_STACK_BASE_ADDR:_equ_0h SYSTEM_LARGE_MEMORY_MODEL:_equ_1 SYSTEM_SMALL_MEMORY_MODEL:_equ_0 IMAGECRAFT:_equ_1 HITECH:_equ_2 TOOLCHAIN:_equ_IMAGECRAFT 
SYSTEM_TOOLS=1
CSFLOW=
CONFIG_NAMES=rpi_robot 
